export const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
export const INIT_NEW_BOARD = 'INIT_NEW_BOARD';
export const SUBMIT_NEW_BOARD_TO_COLLECTION = 'STORE_NEW_BOARD_TO_COLLECTION';
export const UPDATE_POSITION_BOARD_IN_COLLECTION = 'UPDATE_POSITION_BOARD_IN_COLLECTION';

export const CREATE_LIST_IN_BOARD = 'CREATE_LIST_IN_BOARD';